### ISSUE TITLE
Fix samplenet.yaml

### ISSUE THREAD

**Issue by MicheleMacagno** [ibm-silvergate/netcomposer#1]
I found this error running the sample with Ubuntu 16.04 Hyperledger Fabric 1.0.2.
Error: Error getting chaincode code chaincode: path to chaincode does not exist: 
github.com/hyperledger/fabric/chaincodes/./go/kv_chaincode_go_example01

I solved by modifying the file https://github.com/ibm-silvergate/netcomposer/blob/master/samplenet.yaml
line 55 from:
path:     go/kv_chaincode_go_example01
to line 55
path:     ./sample-chaincodes/go/kv_chaincode_go_example01

The same must be done at line 62
line 62 from:
#path:     node/kv_chaincode_node_example01
to line 62:
#path:     ./sample-chaincodes/node/kv_chaincode_node_example01

Please Fix.
Thank you

**Comment by erNail** [comment]
For me it's working as intended. I guess the issue can be closed.
