### ISSUE TITLE
Peer node not starting while executing provision script

### ISSUE THREAD

**Issue by erNail** [ibm-silvergate/netcomposer#13]
The peer nodes are currently started with the command `peer node start --peer-defaultchain=false; /bin/bash` in the `docker-compose.yaml.` This causes an error and the issue that the container will exit (No access to logs). Instead, only `peer node start` should be executed.

**Comment by erNail** [comment]
Fixed issue. Waiting for Pull Request #14 to be accepted.

**Comment by jeroiraz** [comment]
Thanks @erNail
