### ISSUE TITLE
Error during provisioning with tls disabled

### ISSUE THREAD

**Issue by erNail** [ibm-silvergate/netcomposer#15]
When provisioning a network with TLS disabled, the following error occurs during `peer channel create`:

```
grpc: addrConn.createTransport failed to connect to {orderer1.samplenet.com:7050 0  <nil>}.
Err :connection error: desc = "transport: authentication handshake failed: tls: 
first record does not look like a TLS handshake". Reconnecting...
```

The cause for this can be found in line 36 in the `provision-template.sh`. During `peer channel create`, there is always the argument `--tls true`. Changing it to false will still cause an error. With TLS disabled, the argument has to be removed completely.

**Comment by erNail** [comment]
Fixed issue. Waiting for Pull Request #16 to be accepted.

**Comment by jeroiraz** [comment]
Thanks for the fix @erNail
