### ISSUE TITLE
During provisioning, delay between commands required for kafka setup

### ISSUE THREAD

**Issue by erNail** [ibm-silvergate/netcomposer#17]
When running the provision script with a kafka setup, when executing `createChannel`, the error `Error: got unexpected status: SERVICE_UNAVAILABLE -- will not enqueue, consenter for this channel hasn't started yet` is thrown. 
The solution for this is a delay between the `startNetwork` and the `createChannel` function. This delay should be configurable either in the yaml, or via parameter for the provision script.

**Comment by erNail** [comment]
Waiting for pull request #29 to be accepted.

**Comment by jeroiraz** [comment]
Thanks @erNail for your contributions. I haven't used the tool for a while, I'll process your improvements
