### ISSUE TITLE
Fix Linux x86

### ISSUE THREAD

**Issue by FrauElster** [ibm-silvergate/netcomposer#19]
`go run main.go -spec `samplenet.yaml` leads to `Copying chaincodes to samplenet/volumes/chaincodes: SUCCEED
Generating crypto config file: SUCCEED
Generating crypto material: fork/exec tools/linux-x86_64/cryptogen: no such file or directory
exit status 1
`

There is no linux-x86 dir in tools

**Comment by erNail** [comment]
Waiting for pull request #23 to be accepted. Thanks to @FrauElster
