### ISSUE TITLE
adding a new org at consortium level

### ISSUE THREAD

**Issue by vu3mmg** [ibm-silvergate/netcomposer#2]
Hi , 
Once I generate the  network and I want to update the network at runtime  by adding orgs at consortium level . How could I do that .
How do I get signatures of the peers  using an API

regards
Mahesh

**Comment by jeroiraz** [comment]
Hi Manesh,
This simple tool is one shot, it will bootstrap based on the spec file. It'd be possible to add peers or even organizations, for instance, creating a new spec file adding the new organizations, peers, channels, chaincodes. I think it will be a nice to have feature, as the possibility to run the peers on different host machines.
The spirit of this tool is to simplify the bootstrap of simple Hyperledger Fabric networks, we should figure out how to add these features without adding complexity to the specification file.
I'll think how to add this feature, but if you or someone else have a proposal, please let us know.

Meanwhile, a workaround would be to create a new spec file, generate the docker-compose file by running the tool, but manually leaving only the new containers in such file. It'll be prone to error, but if you need to solve it before being addressed by the tool it might help.

Cheers,
Jero
