### ISSUE TITLE
provision.sh not relativ path to docker-compose.yaml

### ISSUE THREAD

**Issue by FrauElster** [ibm-silvergate/netcomposer#25]
If provision.sh is executed in netcomposer/out/samplenet/ instead of ./out/samplenet/provision.sh in netcomposer directory, it throws  ERROR: .FileNotFoundError: [Errno 2] No such file or directory: '././out/samplenet/docker-compose.yaml'. 
Path is not relative to script

**Comment by erNail** [comment]
Duplicate of #9. Can be closed.
