### ISSUE TITLE
Crossplatform Windows

### ISSUE THREAD

**Issue by FrauElster** [ibm-silvergate/netcomposer#28]
Make Netcomposer compatible with Win.
This includes 

- removing the binaries from `netcomposer/tools/windows-amd64` and put there the uncompiled go files from hyperledger.
- edit the commands and paths for BATCH commands

**Comment by jeroiraz** [comment]
@FrauElster I think having a dockerized version of this tool might simplify things. What do you think?

**Comment by FrauElster** [comment]
Lol that's so long ago, I didn't even know I made a pull request :D
I have absolutely no clue what and how I did something :D
But yes dockerized sounds good :D

**Comment by FrauElster** [comment]
Oh I didn't made a pr, just an issue...sounds like me :D
