### ISSUE TITLE
Dockerize the Build of the Network Artifacts

### ISSUE THREAD

**Issue by erNail** [ibm-silvergate/netcomposer#33]
It might make sense to dockerize the build of the network artifacts (`go run main.go`). This way, a local go installation is not required. 
It would be simple to realise, we just need a GoLang Docker Container, which has the netcomposer root as volume.

**Comment by jeroiraz** [comment]
yes, it should fetch cryptogen and configtxgen binaries when the image is build. But it will simplify the use of this tool given docker will be already in your dev env
