### ISSUE TITLE
Add feature to choose the names of the orgs

### ISSUE THREAD

**Issue by erNail** [ibm-silvergate/netcomposer#34]
It would be great, if we could choose the name of the organisations, instead of naming them "org1, org2" etc.

**Comment by jeroiraz** [comment]
This utility was meant to easily create local dev networks based on customized or experimental new features. In that sense, adding more features may end-up making config files more complex. But what's your perspective on that @erNail ?

**Comment by erNail** [comment]
Hi @jeroiraz, nice to hear from you. I think at the moment the config file is quite slim, so adding this feature wouldn't blow up anything. 
But in general i agree. Especially with all the new features in Fabric 2.0 it could get very complex.
