### ISSUE TITLE
Error while pulling images (Wrong tag name)

### ISSUE THREAD

**Issue by erNail** [ibm-silvergate/netcomposer#5]
Right now, the tag name consists of `$ARCH-$VERSION`. Since Fabric 1.2 (i think), those tag name is not used anymore for the "x86_64" architecture. For example, the current one for this architecture is "1.3.0".

There are 3 problems with the tag handling at the moment:

- Tag naming conventions can change (No $ARCH variable anymore)
- Thirdparty images (couchdb, zookeeper, kafka) have a different version and tag than the fabric images
- CA image can have a different version and tag than the fabric images (At least it's seperated in the [fabric binaries setup script](https://github.com/hyperledger/fabric/blob/v1.3.0/scripts/bootstrap.sh))

I propose the following:

- [x] In the samplenet.yaml, remove `VERSION` and `ARCH`
- [x] In the samplenet.yaml, add `FABRIC_VERSION_TAG`, `CA_VERSION_TAG`, `THIRDPARTY_VERSION_TAG` (Similiar to the fabric binaries setup script). This prevents a dependency on the tag naming convention.
- [x] In the `pull-docker-images-template.sh`, differentiate between fabric images, ca image and thirdparty images
- [x] In the `docker-compose-template.yaml`, differentiate between fabric images, ca image and thirdparty images

I'm currently implementing these changes. I'll create a Pull Request as soon as i'm done.

**Comment by erNail** [comment]
Fixed, waiting for Pull Request #7 to be accepted.

**Comment by jeroiraz** [comment]
Thanks @erNail
